##
# Node.js installation (latest stable instead of Ubuntu's out-of-date one)
#
- name: Node.js | Package prerequisites for node.js
  action: apt pkg={{ item }} state=installed update-cache=yes
  tags: nodejs
  with_items:
    - python-software-properties
    - python

- name: Node.js | Add the node.js PPA
  apt_repository: repo='ppa:chris-lea/node.js' state=present
  tags: nodejs

- name: Node.js | Update the apt cache for the new repository
  action: apt update-cache=yes
  tags: nodejs

- name: Node.js | Install nodejs
  action: apt pkg={{ item }} state=installed update-cache=yes
  tags: nodejs
  with_items:
    - nodejs
