- name: Ruby | Installs rbenv
  action: git repo=git://github.com/sstephenson/rbenv.git dest=~{{ host.user }}/.rbenv
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Installs rbenv bash file
  copy: src=bash_50_rbenv dest=~{{ host.user }}/.bash_50_rbenv mode=700 owner={{ host.user }}
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Source rbenv bash file in dot bashrc
  lineinfile: dest=~{{ host.user }}/.bash_profile regexp="^source \.bash_50_rbenv" insertafter=EOF line="source .bash_50_rbenv" create=yes
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Creates plugin directory
  action: file path=~{{ host.user }}/.rbenv/plugins/ owner={{ host.user }} group={{ host.user }} mode=0755 state=directory
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Installs ruby-build
  action: git repo=git://github.com/sstephenson/ruby-build.git dest=~{{ host.user }}/.rbenv/plugins/ruby-build
  tags:
    - ruby
    - ruby:install
    - install
