- name: Checks if target ruby is installed
  shell: cd; bash -lc "rbenv versions | grep {{ ruby_version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '"
  register: ruby_is_installed
  changed_when: ruby_is_installed.stdout != ruby_version

- name: Sets fake ruby version for check mode
  set_fact:
    ruby_is_installed: { 'stdout': "{{ruby_version}}" }
  when: ruby_is_installed|skipped

- command: iptables -I OUTPUT -m tcp -p tcp -m multiport --dports 22,80,443,9418 -m comment --comment "ruby-ansible-temp" -j ACCEPT
  sudo: yes
  sudo_user: root
  changed_when: false

- name: Installs ruby
  shell: cd; bash -lc "MAKEOPTS={{ ruby_makeopts }} CONFIGURE_OPTS="--disable-install-rdoc" rbenv install {{ ruby_version }}"
  when: ruby_is_installed.stdout != ruby_version
  # Takes no more than 600 secs on a small VM
  async: 900
  poll: 30

- name: Installs bundler for new ruby
  shell: cd; bash -lc "rbenv local {{ ruby_version }} && gem install bundler"
  when: ruby_is_installed.stdout != ruby_version
  register: new_ruby_installed

- command: iptables -D OUTPUT -m tcp -p tcp -m multiport --dports 22,80,443,9418 -m comment --comment "ruby-ansible-temp" -j ACCEPT
  sudo: yes
  sudo_user: root
  changed_when: false

- name: Set global rbenv version
  shell: cd; bash -lc "rbenv global {{ ruby_version }}"
  when: new_ruby_installed|changed

