- name: PostgreSQL Ext | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    port: "{{postgresql_port}}"
    state: present
    login_host: "{{item.host | default('localhost')}}"
    login_user: "{{postgresql_admin_user}}"
    role_attr_flags: "{{item.role_attr_flags | default('')}}"
  sudo: yes
  sudo_user: "{{postgresql_admin_user}}"
  with_items: postgresql_ext_user_privileges
  when: postgresql_users|length > 0
