---
# Initializes custom user
- name: Ensure DB user has access to the DB
  postgresql_user: name={{ postgresql.custom.user }}
                   password={{ postgresql.custom.password }}
                   role_attr_flags={{ postgresql.custom.role_attrs }} state=present
  sudo: yes
  sudo_user: postgres
  tags:
    - postgresql
    - user:setup
