galaxy_info:
  author: Michel Blanc
  description: compiled-ruby role
  company: ERASME/Grand-Lyon Métropole
  license: MIT
  min_ansible_version: 1.8

  platforms:
  - name: Ubuntu
    versions:
      - all
  - name: Debian
    versions:
      - all
  categories:
    - development

dependencies:
 - role: erasme.rbenv

