- hosts: vagrant
  sudo: true
  roles:
    - common
    - git
    - postgresql
    - ANXS.postgresql
    - postgresql-ext
    - imagemagick
    - erasme.rbenv
    - erasme.ruby-compiled
    - redis
    - oh_my_zsh
