- hosts: vagrant
  sudo: true
  roles:
    - common
    - git
    - ANXS.postgresql
    - postgresql-ext
    - imagemagick
    - erasme.rbenv
    - erasme.ruby-compiled
    - DavidWittman.redis
    - oh_my_zsh
