- name: Add .gitignore_global
  copy: src=gitignore_global dest=~/.gitignore_global mode=0644
  tags:
    - git

- name: Config git to use global gitignore file
  shell: cd; bash -lc "git config --global core.excludesfile '~/.gitignore_global'"
  tags:
    - git

- name: Configure user's name
  shell: cd; bash -lc "git config --global user.name '{{ git.name }}'"
  when: git.name is defined
  tags:
    - git

- name: Configure user's email
  shell: cd; bash -lc "git config --global user.email '{{ git.email }}'"
  when: git.email is defined
  tags:
    - git
